apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: my-crud-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"   # MySQL service name
        - name: DB_USER
          value: "root"    # MySQL root user
        - name: DB_PASSWORD
          value: ""        # Empty password (since no password is used)
        readinessProbe:
          httpGet:
            path: /health  # Adjust the path according to your API
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10